# Generated by Django 2.0.2 on 2019-12-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='get_category', to='blog.Category', verbose_name='Categorias'),
        ),
    ]
