# Generated by Django 2.0.2 on 2020-01-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.AddField(
            model_name='recomendation',
            name='state',
            field=models.ManyToManyField(related_name='get_state', to='recomendations.State', verbose_name='Estado'),
        ),
    ]
